config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update] # probably want to keep using this

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # # GET /users/1
  # # GET /users/1.json
  def show
    
  end

  # GET /users/1/edit
  def edit

  end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:role, :user_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biztags_helper.rb
module BiztagsHelper
end

app/helpers/boroughs_helper.rb
module BoroughsHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<h1>This is the app's landing page!</h1>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit Settings', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
   <%= link_to "Profile", current_user %> <!-- link to show user profile / edit profile -->
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consign</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>


<%= render 'layouts/header' %>


<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<!--   <%# if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <%# @user.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %> -->



<!-- this needs to be set to a radio button -->
  <div class="field">
    <%= f.label :role %><br> 
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_area :user_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your User settings</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
      <th>User Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.user_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%#= link_to 'Edit', edit_user_path(user) %></td>
        <td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New User', new_user_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>user show page</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.user_name %>
</p>

<!-- include businesses, etc. -->

<%= link_to 'Edit Profile', edit_user_path(@user) %> |
<%#= link_to "Settings", edit_user_path %>